// Code generated by "stringer -type=EventStart"; DO NOT EDIT.

package holiday

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Sunset-0]
	_ = x[Nightfall-1]
	_ = x[Dawn-2]
}

const _EventStart_name = "SunsetNightfallDawn"

var _EventStart_index = [...]uint8{0, 6, 15, 19}

func (i EventStart) String() string {
	if i >= EventStart(len(_EventStart_index)-1) {
		return "EventStart(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventStart_name[_EventStart_index[i]:_EventStart_index[i+1]]
}
