// Code generated by "stringer -type=Leap"; DO NOT EDIT.

package hebcal

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LeapNext-0]
	_ = x[LeapNone-1]
	_ = x[LeapPrev-2]
}

const _Leap_name = "LeapNextLeapNoneLeapPrev"

var _Leap_index = [...]uint8{0, 8, 16, 24}

func (i Leap) String() string {
	if i < 0 || i >= Leap(len(_Leap_index)-1) {
		return "Leap(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Leap_name[_Leap_index[i]:_Leap_index[i+1]]
}
